### ISSUE TITLE
Fail to install lm-sensors package

### ISSUE THREAD

**Issue by openstacks** [blueboxgroup/ursula#1075]
#ursula envs/example/allinone site.yml --ursula-debug

TASK: [common | install lm-sensors package] ***********************************
Monday 20 July 2015  13:46:40 +0000 (0:00:00.152)       0:00:19.887 ***********
failed: [10.110.8.172] => {"failed": true}
msg: Could not fetch updated apt files

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
Monday 20 July 2015  13:46:46 +0000 (0:00:06.071)       0:00:25.959 ***********
===============================================================================
Slowest 25 Tasks
===============================================================================
common | install lm-sensors package ------------------------------------- 6.07s
common | update apt index ----------------------------------------------- 3.65s
common | install system tools ------------------------------------------- 0.80s
common | remove older libruby ------------------------------------------- 0.78s
common | blacklist mei -------------------------------------------------- 0.15s
apt-repos | add any dependent repository keys from url ------------------ 0.01s
apt-repos | add any dependent repository key packages ------------------- 0.01s
apt-repos | add any dependent repositories ------------------------------ 0.01s
common | load vlan module ----------------------------------------------- 0.00s
common | ignore proxy for localhost ------------------------------------- 0.00s
common | add global proxy ----------------------------------------------- 0.00s
docker | install docker ------------------------------------------------- 0.00s
common | ubuntu apt source list ----------------------------------------- 0.00s
common | add an apt proxy ----------------------------------------------- 0.00s
common | set hostname --------------------------------------------------- 0.00s
           to retry, use: --limit @/root/site.retry

10.110.8.172               : ok=11   changed=0    unreachable=0    failed=1

**Comment by openstacks** [comment]
root@hkg02kvm002ccz023:/cloud/ursula# apt-cache show lm-sensors
Package: lm-sensors
Priority: extra
Section: universe/utils
Installed-Size: 401
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Aurelien Jarno <aurel32@debian.org>
Architecture: amd64
Version: 1:3.3.1-2ubuntu1
Depends: sed (>= 4.0.5-1), lsb-base (>= 3.2-13), libc6 (>= 2.3.4), libsensors4 (>= 1:3.1.1), perl
Suggests: fancontrol, sensord, read-edid, i2c-tools
Filename: pool/universe/l/lm-sensors/lm-sensors_3.3.1-2ubuntu1_amd64.deb
Size: 100702
MD5sum: faaba9b471547256f877781836ce8f29
SHA1: c92fae5bf22a0cb9e1117a535485ec09d7919cf3
SHA256: a5d0a819c78675e86b8154037a29192e74275d55ead822ca001965b75b3a740d
Description-en: utilities to read temperature/voltage/fan sensors
 Lm-sensors is a hardware health monitoring package for Linux. It allows you
 to access information from temperature, voltage, and fan speed sensors. It
 works with most newer systems.
 .
 This package contains programs to help you set up and read data from
 lm-sensors.
Homepage: http://www.lm-sensors.org
Description-md5: 491418ae94ae096e9d6b05b0cf47c351
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu

**Comment by paulczar** [comment]
this looks related to your other bug.  if `apt-get update` cannot run I would expect to see issues like this pop up.
