### ISSUE TITLE
packagecloud repo doesn't work

### ISSUE THREAD

**Issue by openstacks** [blueboxgroup/ursula#1077]
Fail to install package after packagecloud repo is installed.
Here are test steps
1; install a packagecloud repo following steps in this link   
    https://packagecloud.io/blueboxcloud/giftwrap/install
   1.1: quick install
      curl -s https://packagecloud.io/install/repositories/blueboxcloud/giftwrap/script.deb.sh | sudo
         bash
      root@# curl -s https://packagecloud.io/install/repositories/blueboxcloud/giftwrap/script.deb.sh | 
               sudo bash
            Detected operating system as Ubuntu/precise.
            Checking for curl...
            Detected curl...
            Installing apt-transport-https... done.
            Getting the hostname of this machine...
            Found hostname: hkg02kvm002ccz023.ccz023.hkg02.ibm.com
            Installing /etc/apt/sources.list.d/blueboxcloud_giftwrap.list...  % Total    % Received % Xferd   
            Average Speed   Time    Time     Time  Current
            Dload  Upload   Total   Spent    Left  Speed
           100   262    0   262    0     0    343      0 --:--:-- --:--:-- --:--:--   426
           done.
           Importing packagecloud gpg key... done.
           Running apt-get update... done.
          You have new mail in /var/mail/root

   2.2:check the repo 
        cat /etc/apt/sources.list.d/blueboxcloud_giftwrap.list
        # this file was generated by packagecloud.io for
        # the repository at https://packagecloud.io/blueboxcloud/giftwrap
       deb https://packagecloud.io/blueboxcloud/giftwrap/ubuntu/ precise main
       deb-src https://packagecloud.io/blueboxcloud/giftwrap/ubuntu/ precise main

3: Install package
    # apt-get install openstack-keystone-11.0-bbc73=11.0-bbc73
    root@ursula# apt-get install openstack-keystone-11.0-bbc73=11.0- bbc73
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    E: Unable to locate package openstack-keystone-11.0-bbc73
    E: Couldn't find any package by regex 'openstack-keystone-11.0-bbc73'

**Comment by j2sol** [comment]
This repo is no longer in use.
