### ISSUE TITLE
os_subnet is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by pbannister** [blueboxgroup/ursula#1093]
Checked out current "master" (a311437a1ce91c8e710b34783b35aeacf452294a). Followed the instructions to bring up "allinone". (I have done this successfully before, with an older version.) Got an error:

```
bin/run_vagrant up allinone
[snip]
    allinone: /vagrant => /Users/preston/projects/ursula
==> allinone: Machine not provisioning because `--no-provision` is specified.
running ursula --ursula-debug envs/example/allinone site.yml --extra-vars @envs/example/vagrant.yml -s -u vagrant
DEBUG: Running command: ansible-playbook --inventory-file envs/example/allinone/hosts --user root --module-path ./library site.yml --extra-vars @envs/example/vagrant.yml -s -u vagrant with environment: {'PYTHONIOENCODING': 'UTF-8', 'PROJECT_HOME': '/Users/preston/projects', 'VERSIONER_PYTHON_PREFER_32_BIT': 'no', 'TERM_PROGRAM_VERSION': '343.7', 'LOGNAME': 'preston', 'USER': 'preston', 'HOME': '/Users/preston', 'PATH': '/Users/preston/.virtualenvs/ursula/bin:/usr/local/narwhal/bin:/Users/preston/bin:/usr/local/bin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin', 'PYTHONUNBUFFERED': '1', 'VIRTUALENVWRAPPER_SCRIPT': '/usr/local/bin/virtualenvwrapper.sh', 'NARWHAL_ENGINE': 'jsc', 'DISPLAY': '/private/tmp/com.apple.launchd.LC4Ey4GNwr/org.macosforge.xquartz:0', 'TERM_PROGRAM': 'Apple_Terminal', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm-256color', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.j3sCRzgGUV/Render', 'VERSIONER_PYTHON_VERSION': '2.7', 'SHLVL': '2', 'SECURITYSESSIONID': '186a5', 'XPC_FLAGS': '0x0', '_': '/Users/preston/.virtualenvs/ursula/bin/ursula', 'WORKON_HOME': '/Users/preston/.virtualenvs', 'TERM_SESSION_ID': '1AA79404-1B54-4E38-A6A8-70692609448E', 'XPC_SERVICE_NAME': '0', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.MjUGCQ7rXq/Listeners', 'VIRTUAL_ENV': '/Users/preston/.virtualenvs/ursula', 'DYLD_LIBRARY_PATH': '/usr/local/mysql/lib:', 'URSULA_ENV': '/Users/preston/projects/ursula/envs/example/allinone', 'SHELL': '/bin/bash', 'ANSIBLE_FORCE_COLOR': 'yes', 'SETTINGS_FILE': 'envs/example/allinone/vagrant.yml', 'TMPDIR': '/var/folders/nz/q0s01cks58ngv5tdl8x1_fpm0000gn/T/', 'VIRTUALENVWRAPPER_PROJECT_FILENAME': '.project', 'VIRTUALENVWRAPPER_HOOK_DIR': '/Users/preston/.virtualenvs', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'PWD': '/Users/preston/projects/ursula', 'ANSIBLE_SSH_ARGS': ' -F .vagrant/allinone.ssh -o ControlMaster=auto -o ControlPath=~/.ssh/controlmasters/u-%r@%h:%p -o ControlPersist=300', 'CAPP_BUILD': '/Users/preston/Downloads/Build', 'ANSIBLE_VAR_DEFAULTS_FILE': 'envs/example/allinone/../defaults.yml'}
ERROR: os_subnet is not a legal parameter in an Ansible task or handler
```

The commit that *seems* to have caused the problem is:

https://github.com/blueboxgroup/ursula/blob/3e30ff769848a5bec18ad449b2383c8dec8da908/roles/openstack-setup/tasks/networks.yml

**Comment by j2sol** [comment]
So you'll get this if the ansible you're calling doesn't have the modules installed. Master requires a Blue Box fork of Ansible that pulls in a fork of ansible-modules-core that backports a number of the new Open Stack modules (os_*). If you install the requirements in requirements.txt you should get this version of Ansible and modules.

**Comment by pbannister** [comment]
Did pull in the requirements, but missed an error? Digging...


(ursula)hermes:ursula preston$ pip install -U -r requirements.txt
Requirement already up-to-date: python-novaclient in
/Users/preston/.virtualenvs/ursula/lib/python2.7/site-packages (from
-r requirements.txt (line 1))
Requirement already up-to-date: python-neutronclient in
/Users/preston/.virtualenvs/ursula/lib/python2.7/site-packages (from
-r requirements.txt (line 2))
Requirement already up-to-date: python-keystoneclient in
/Users/preston/.virtualenvs/ursula/lib/python2.7/site-packages (from
-r requirements.txt (line 3))
Requirement already up-to-date: python-glanceclient in
/Users/preston/.virtualenvs/ursula/lib/python2.7/site-packages (from
-r requirements.txt (line 4))
Requirement already up-to-date: python-cinderclient in
/Users/preston/.virtualenvs/ursula/lib/python2.7/site-packages (from
-r requirements.txt (line 5))
Requirement already up-to-date: oslo.utils in
/Users/preston/.virtualenvs/ursula/lib/python2.7/site-packages (from
-r requirements.txt (line 6))
Requirement already up-to-date: tox in
/Users/preston/.virtualenvs/ursula/lib/python2.7/site-packages (from
-r requirements.txt (line 7))
Requirement already up-to-date: pep8 in
/Users/preston/.virtualenvs/ursula/lib/python2.7/site-packages (from
-r requirements.txt (line 8))
Obtaining ansible-lint from
git+git://github.com/willthames/ansible-lint.git@9777f20aafd4be8706c9ce17005c981cb19a6a25#egg=ansible-lint
(from -r requirements.txt (line 9))
  Updating /Users/preston/.virtualenvs/ursula/src/ansible-lint clone
(to 9777f20aafd4be8706c9ce17005c981cb19a6a25)
  Could not find a tag or branch
'9777f20aafd4be8706c9ce17005c981cb19a6a25', assuming commit.
  Running setup.py
(path:/Users/preston/.virtualenvs/ursula/src/ansible-lint/setup.py)
egg_info for package ansible-lint
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267:
UserWarning: Unknown distribution option: 'include_package_date'
      warnings.warn(msg)

  Installing extra requirements: 'egg'
Obtaining ansible from
git+git://github.com/blueboxgroup/ansible.git@stable-1.9-bb#egg=ansible
(from -r requirements.txt (line 10))
  Updating /Users/preston/.virtualenvs/ursula/src/ansible clone (to
stable-1.9-bb)
fatal: reference is not a tree: d9102b8cb4b0025444449a5ca9e9a928e45f6c38
Unable to checkout 'd9102b8cb4b0025444449a5ca9e9a928e45f6c38' in
submodule path 'lib/ansible/modules/core'
  Complete output from command /usr/bin/git submodule update --init
--recursive -q:

----------------------------------------
Cleaning up...
Command /usr/bin/git submodule update --init --recursive -q failed
with error code 1 in /Users/preston/.virtualenvs/ursula/src/ansible
Storing debug log for failure in /Users/preston/.pip/pip.log

**Comment by j2sol** [comment]
Looks like the bit that tries to initialize the submodules (where ansible-modules-core and extras) comes from is failing on your system for some reason.

**Comment by pbannister** [comment]
The requirements item that fails:

```
(ursula)hermes:ursula preston$ pip install -e git://github.com/blueboxgroup/ansible.git@stable-1.9-bb#egg=ansible
Obtaining ansible from git+git://github.com/blueboxgroup/ansible.git@stable-1.9-bb#egg=ansible
  Updating /Users/preston/.virtualenvs/ursula/src/ansible clone (to stable-1.9-bb)
fatal: reference is not a tree: d9102b8cb4b0025444449a5ca9e9a928e45f6c38
Unable to checkout 'd9102b8cb4b0025444449a5ca9e9a928e45f6c38' in submodule path 'lib/ansible/modules/core'
  Complete output from command /usr/bin/git submodule update --init --recursive -q:
  
----------------------------------------
Cleaning up...
Command /usr/bin/git submodule update --init --recursive -q failed with error code 1 in /Users/preston/.virtualenvs/ursula/src/ansible
Storing debug log for failure in /Users/preston/.pip/pip.log
```

**Comment by pbannister** [comment]
Perhaps you did not (yet) push a submodule (the one containing d9102b8cb4b0025444449a5ca9e9a928e45f6c38)?

http://stackoverflow.com/a/2161389/184534

**Comment by j2sol** [comment]
I don't think that's the case. I've tested in brand new virtualenvs and they're able to get everything installed.

**Comment by pbannister** [comment]
Dug down a bit. Cannot say I am fluent with the git submodule, but this looks like a clue...

Cloned bluebox/ansible and checked out "devel". (OK)
```
hermes:bluebox-ansible preston$ git checkout devel 
Already on 'devel'
Your branch is up-to-date with 'origin/devel'.
hermes:bluebox-ansible preston$ git submodule update --init --recursive
```

Checked out the "stable-1.9-bb" branch, and *attempted* to update the submodules. (Note the last line.)
```
hermes:bluebox-ansible preston$ git checkout stable-1.9-bb
M	lib/ansible/modules/core
M	lib/ansible/modules/extras
M	v2/ansible/modules/core
M	v2/ansible/modules/extras
Switched to branch 'stable-1.9-bb'
hermes:bluebox-ansible preston$ git submodule update --init --recursive
fatal: reference is not a tree: d9102b8cb4b0025444449a5ca9e9a928e45f6c38
Submodule path 'lib/ansible/modules/extras': checked out 'f8f2ba8c355e9be8576e733482835f11013e65ff'
Submodule path 'v2/ansible/modules/core': checked out '85c8a892c80b92730831d95fa654ef6d35b0eca0'
Submodule path 'v2/ansible/modules/extras': checked out '70ea05856356ad36f48b4bb7267d637efc56d292'
Unable to checkout 'd9102b8cb4b0025444449a5ca9e9a928e45f6c38' in submodule path 'lib/ansible/modules/core'
```

Dropped into "lib/ansible/modules/core" and indeed d9102b8cb4b0025444449a5ca9e9a928e45f6c38 does not appear in 'git log'. Given this is a fresh clone from github, do not see have this could be local.

Why this would succeed on your box ... dunno.

**Comment by pbannister** [comment]
Apparently `git submodule` support does not handle changing the URL to a submodule. 
Or at least not well.

Found that the `git submodule update` does badly when the parent changes the submodule URL. The URL in the submodule does *not* get updated.

(Perhaps there is a workaround for this in *pip*? I have pip 1.5.6 installed.) 

First, wrote a script to do a repeatable clean install of *ursula*, and bring up *allinone*.
```
#!/bin/bash

source /usr/local/bin/virtualenvwrapper.sh

cd $PROJECT_HOME || {
	echo "Cannot use PROJECT_HOME!!"
	exit 1
}

test -e ursula && {
	( cd ursula && vagrant destroy -f allinone )
	rm -rf ursula
}

test -e ursula && {
	echo "Cannot remove ursula project directory!"
	exit 1
}

echo "Remove virtual environment..."
rmvirtualenv ursula

mkproject ursula
cd $PROJECT_HOME/ursula || {
	echo "Cannot make project!"
	exit 2
}

git clone git@github.com:blueboxgroup/ursula.git . || {
	echo "Cannot clone ursula from git!"
	exit 3
}

pip install -vv --log /tmp/pip.log -r requirements.txt || {
	echo "Cannot install requirements!"
	exit 4
}

bin/run_vagrant up allinone || {
	echo "Cannot create/start allinone!"
	exit 5
}
```
This failed (as before).

Went into the `lib/ansible/modules/core/` in the virtualenv, dumped `.gitconfig`, and found the repository URL pointing at the ansible (not bluebox) version.

(I saw this before with the `git checkout` and `git submodule update` sequence when switching between branches.)

Added a `pip install -U pip` rule to the script (in case *pip* has a workaround), and rerunning...

**Comment by pbannister** [comment]
... and that did it. Updating `pip` in the virtualenv from 1.5.6 to 7.1.0 (the current), and can bring up `allinone` w/o trouble. Apparently the later version of `pip` has a workaround for the `git submodule update` behavior.

The updated script, for reference.
```
#!/bin/bash

source /usr/local/bin/virtualenvwrapper.sh

cd $PROJECT_HOME || {
	echo "Cannot use PROJECT_HOME!!"
	exit 1
}

test -e ursula && {
	( cd ursula && vagrant destroy -f allinone )
	rm -rf ursula
}

test -e ursula && {
	echo "Cannot remove ursula project directory!"
	exit 1
}

echo "Remove virtual environment..."
rmvirtualenv ursula

mkproject ursula
cd $PROJECT_HOME/ursula || {
	echo "Cannot make project!"
	exit 2
}

# Update PIP for this project.
pip install -U pip

git clone git@github.com:blueboxgroup/ursula.git . || {
	echo "Cannot clone ursula from git!"
	exit 3
}

pip install -vv --log /tmp/pip.log -r requirements.txt || {
	echo "Cannot install requirements!"
	exit 4
}

bin/run_vagrant up allinone || {
	echo "Cannot create/start allinone!"
	exit 5
}
```

(Can you add a `pip` version to `requirements.txt` in any meaningful way?)

**Comment by pbannister** [comment]
FWIW, you can close this if you want. Might want to document the dependency on a later(?) version of `pip`, and mention the `git submodule` trouble. Not sure if this is something that `requirements.txt` can handle.

**Comment by j2sol** [comment]
Thanks for digging through it. I'll update the readme.


- jlk

**Comment by mmedvede** [comment]
Update to requirements (e.g. adding 'pip>=7.0) would not help, because when you run pip install -r it would still use the old pip binary. Running 'mkvirtualenv ursula && pip install pip -U' works fine. I do not think README was updated.

**Comment by sebrandon1** [comment]
I'm receiving this error now as well.  "ERROR: os_subnet is not a legal parameter in an Ansible task or handler".

I've followed the README exactly and I'm still getting the error.

**Comment by j2sol** [comment]
Usually the root cause of this is the virtualenv construction to run
ursula, et al, in. You need to have a decently recent version of
vritualenv, or you need to be sure to upgrade pip inside the virtualenv
before installing the rest. You also need to pass whatever appropriate
option there is to not use wheels. With all of that, installing ursula's
requirements should result in a functional ansible.


- jlk
