### ISSUE TITLE
Swift deployment fails when install method is source

### ISSUE THREAD

**Issue by ryshah** [blueboxgroup/ursula#1154]
restart swift handlers are not defined for Swift causing swift setup task to fail. Looking in to that to get it working.

**Comment by j2sol** [comment]
Can you give some more details?

**Comment by ryshah** [comment]
restart swift service handlers are not defined for Swift causing swift setup task to fail. Looking in to that to get it working.

**Comment by j2sol** [comment]
Each swift sub-role (such as swift-account, swift-container, swift-object, and swift-proxy) all have their own handlers defined for restarting those specific swift services. Please tell me which of the handlers you're seeing get called that isn't defined.

**Comment by ryshah** [comment]
@j2sol When trying out source install it failed 1st time (worked fine on 2nd try) when trying to notify task "restart swift services"... I am working on change to add that task and also one minor change to get Swift source deploy working

**Comment by ryshah** [comment]
Should be fixed with #1171
