### ISSUE TITLE
Default credentials to connect to Horizon dashboard

### ISSUE THREAD

**Issue by fbarilla** [blueboxgroup/ursula#1168]
We just deployed OpenStack using Ursula (using Vagrant). What are the credentials to connect to the Horizon dashboard ?

**Comment by twaldrop** [comment]
You should find the credentials on each of the hypervisors in hosts in /root/stackrc

**Comment by fbarilla** [comment]
Thanks for the info. We are able to get access to the BlueBox dashboard but when we enter the credentials we got a 'Connection Reset'. When we enter a wrong password, we have the expected error message 'Invalid userid/password'. Any idea ?

**Comment by j2sol** [comment]
No ideas. This are working okay on the master branch.
