### ISSUE TITLE
Eventlet version 0.15.2 doesn't work with Swift kilo source install

### ISSUE THREAD

**Issue by ryshah** [blueboxgroup/ursula#1205]
With Kilo release, Swift has updated the version of eventlet library to >= 0.16.1 (& != 0.17.0)... This causes Swift services to not start with version conflict error.. Note: Version 0.15.2 in Ursula is deployed for Nova

**Comment by j2sol** [comment]
When doing source installs, everything is mixed together, but with packages every project gets its own virtualenv.

Our pin for nova's eventlet is most likely based on old versions of Nova, so I would say remove the pinning and see if everything sorts itself out.

**Comment by ryshah** [comment]
Sounds good @j2sol .. we are deploying environment with eventlet unpinned... Will create 1-line PR to unpin eventlent if the change causes no trouble

**Comment by ryshah** [comment]
@j2sol Removed the pinning for latest source install and things work fine. Should I create PR with unpinned source? I heard rumbling about each project will have virtualenv with source as well... Would that change anything?

**Comment by j2sol** [comment]
Please do the PR. In the case of source venvs it'll just mean that they aren't pinned within the venv either.

**Comment by ryshah** [comment]
@j2sol Created PR #1241 for the changes. Please review

**Comment by ryshah** [comment]
PR #1241 is merged
