### ISSUE TITLE
Horizon logs are not forwarded to logstash

### ISSUE THREAD

**Issue by j2sol** [blueboxgroup/ursula#1328]
The logs are winding up in /var/log/apache2/ but do not get into logstash. This prevents being able to easily diagnose issues with Horizon.

**Comment by epwn** [comment]
ill make this noted at scrum if it doesnt come up before then. thanks @j2sol

**Comment by davidcusatis** [comment]
https://github.com/blueboxgroup/ursula/pull/1330
