### ISSUE TITLE
glance cannot retrieve image

### ISSUE THREAD

**Issue by rafaelfolco** [blueboxgroup/ursula#1333]
Just deployed all-in-one manual setup. 
ISSUE: Cannot start instances due to glanceclient issue: glance image-list works, but image-show fails. 

root@bluebox-allinone:~# glance --debug image-show 6e1f67e7-90e8-4fd3-a5d5-e8225f3ea929
curl -g -i -X HEAD -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'User-Agent: python-glanceclient' -H 'Connection: keep-alive' -H 'X-Auth-Token: {SHA1}87fae7c169dff8701d78cfacdae7d88386518cfd' -H 'Content-Type: application/octet-stream'  --cacert /opt/stack/ssl/openstack.crt  --cert None --key None https://bluebox-allinone.novalocal:9393/v1/images/6e1f67e7-90e8-4fd3-a5d5-e8225f3ea929

HTTP/1.1 200 OK
Content-Length: 0
X-Image-Meta-Status: active
X-Image-Meta-Owner: a909f0ecbe86421ab8f4dbf2e0a2cd85
X-Image-Meta-Name: cirros-x86_64
X-Image-Meta-Container_format: ami
X-Image-Meta-Created_at: 2015-11-03T20:10:22.000000
Etag: ee1eca47dc88f4879d8a229cc70a07c6
X-Image-Meta-Min_ram: 0
X-Image-Meta-Updated_at: 2015-11-03T20:10:23.000000
X-Image-Meta-Property-Description: cirros x86_64
X-Image-Meta-Id: 6e1f67e7-90e8-4fd3-a5d5-e8225f3ea929
X-Image-Meta-Property-Architecture: x86_64
Date: Wed, 04 Nov 2015 00:45:10 GMT
X-Openstack-Request-Id: req-23563b43-06c5-4b7b-8648-5e6b58c889b3
X-Image-Meta-Deleted: False
X-Image-Meta-Checksum: ee1eca47dc88f4879d8a229cc70a07c6
X-Image-Meta-Protected: False
X-Image-Meta-Min_disk: 0
X-Image-Meta-Size: 13287936
Connection: close
X-Image-Meta-Is_public: True
Content-Type: text/html; charset=UTF-8
X-Image-Meta-Disk_format: ami

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/shell.py", line 652, in main
    args.func(client, args)
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/v1/shell.py", line 142, in do_image_show
    image_id = utils.find_resource(gc.images, args.image).id
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/openstack/common/apiclient/base.py", line 491, in __getattr__
    self.get()
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/openstack/common/apiclient/base.py", line 509, in get
    new = self.manager.get(self.id)
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/openstack/common/apiclient/base.py", line 494, in __getattr__
    raise AttributeError(k)
AttributeError: id
id

root@bluebox-allinone:~# nova --debug boot --image cirros-x86_64 --flavor 2 test
DEBUG (session:195) REQ: curl -g -i --cacert "/opt/stack/ssl/openstack.crt" -X GET https://bluebox-allinone.novalocal:5001/v2.0 -H "Accept: application/json" -H "User-Agent: python-keystoneclient"
INFO (connectionpool:756) Starting new HTTPS connection (1): bluebox-allinone.novalocal
DEBUG (connectionpool:387) "GET /v2.0 HTTP/1.1" 200 353
DEBUG (session:224) RESP: [200] Date: Wed, 04 Nov 2015 00:47:11 GMT Vary: X-Auth-Token Content-Length: 353 Content-Type: application/json Connection: close
RESP BODY: {"version": {"status": "stable", "updated": "2014-04-17T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v2.0+json"}], "id": "v2.0", "links": [{"href": "https://bluebox-allinone.novalocal:5001/v2.0/", "rel": "self"}, {"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}]}}

DEBUG (v2:76) Making authentication request to https://bluebox-allinone.novalocal:5001/v2.0/tokens
INFO (connectionpool:242) Resetting dropped connection: bluebox-allinone.novalocal
DEBUG (connectionpool:387) "POST /v2.0/tokens HTTP/1.1" 200 3495
DEBUG (session:195) REQ: curl -g -i --cacert "/opt/stack/ssl/openstack.crt" -X GET https://bluebox-allinone.novalocal:8777/v2/a909f0ecbe86421ab8f4dbf2e0a2cd85/images -H "User-Agent: python-novaclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}633527f6532cdc2d09b49363043e5e14dff6d8a6"
INFO (connectionpool:756) Starting new HTTPS connection (1): bluebox-allinone.novalocal
DEBUG (connectionpool:387) "GET /v2/a909f0ecbe86421ab8f4dbf2e0a2cd85/images HTTP/1.1" 200 1053
DEBUG (session:224) RESP: [200] Date: Wed, 04 Nov 2015 00:47:12 GMT Connection: close Content-Type: application/json Content-Length: 1053 X-Compute-Request-Id: req-44953cf7-791f-4d2c-a687-294b39e2a8ca
RESP BODY: {"images": [{"id": "6e1f67e7-90e8-4fd3-a5d5-e8225f3ea929", "links": [{"href": "http://bluebox-allinone.novalocal:8777/v2/a909f0ecbe86421ab8f4dbf2e0a2cd85/images/6e1f67e7-90e8-4fd3-a5d5-e8225f3ea929", "rel": "self"}, {"href": "http://bluebox-allinone.novalocal:8777/a909f0ecbe86421ab8f4dbf2e0a2cd85/images/6e1f67e7-90e8-4fd3-a5d5-e8225f3ea929", "rel": "bookmark"}, {"href": "http://9.114.111.93:9292/images/6e1f67e7-90e8-4fd3-a5d5-e8225f3ea929", "type": "application/vnd.openstack.image", "rel": "alternate"}], "name": "cirros-x86_64"}, {"id": "cb2b4847-7301-4c2f-8b29-d3bb621c5709", "links": [{"href": "http://bluebox-allinone.novalocal:8777/v2/a909f0ecbe86421ab8f4dbf2e0a2cd85/images/cb2b4847-7301-4c2f-8b29-d3bb621c5709", "rel": "self"}, {"href": "http://bluebox-allinone.novalocal:8777/a909f0ecbe86421ab8f4dbf2e0a2cd85/images/cb2b4847-7301-4c2f-8b29-d3bb621c5709", "rel": "bookmark"}, {"href": "http://9.114.111.93:9292/images/cb2b4847-7301-4c2f-8b29-d3bb621c5709", "type": "application/vnd.openstack.image", "rel": "alternate"}], "name": "cirros"}]}

DEBUG (session:195) REQ: curl -g -i --cacert "/opt/stack/ssl/openstack.crt" -X GET https://bluebox-allinone.novalocal:8777/v2/a909f0ecbe86421ab8f4dbf2e0a2cd85/images/6e1f67e7-90e8-4fd3-a5d5-e8225f3ea929 -H "User-Agent: python-novaclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}633527f6532cdc2d09b49363043e5e14dff6d8a6"
INFO (connectionpool:242) Resetting dropped connection: bluebox-allinone.novalocal
DEBUG (connectionpool:387) "GET /v2/a909f0ecbe86421ab8f4dbf2e0a2cd85/images/6e1f67e7-90e8-4fd3-a5d5-e8225f3ea929 HTTP/1.1" 500 128
DEBUG (session:224) RESP:
DEBUG (shell:914) The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-e8febb47-3524-4466-b440-853a0cec405a)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/novaclient/shell.py", line 911, in main
    OpenStackComputeShell().main(argv)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/shell.py", line 838, in main
    args.func(self.cs, args)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/v2/shell.py", line 495, in do_boot
    boot_args, boot_kwargs = _boot(cs, args)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/v2/shell.py", line 142, in _boot
    image = _find_image(cs, args.image)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/v2/shell.py", line 1894, in _find_image
    return utils.find_resource(cs.images, image)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/utils.py", line 216, in find_resource
    return manager.find(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/base.py", line 196, in find
    matches = self.findall(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/base.py", line 258, in findall
    found.append(self.get(obj.id))
  File "/usr/local/lib/python2.7/dist-packages/novaclient/v2/images.py", line 53, in get
    return self._get("/images/%s" % base.getid(image), "image")
  File "/usr/local/lib/python2.7/dist-packages/novaclient/base.py", line 156, in _get
    _resp, body = self.api.client.get(url)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/adapter.py", line 170, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 96, in request
    raise exceptions.from_response(resp, body, url, method)
ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-e8febb47-3524-4466-b440-853a0cec405a)
ERROR (ClientException): The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-e8febb47-3524-4466-b440-853a0cec405a)

**Comment by j2sol** [comment]
This is an issue with python-glanceclient and urllib3 (as delivered by the requests library). Downgrade your requests to 2.7.0 where you are running glance client and this should clear up.

**Comment by rafaelfolco** [comment]
For the record: The downgrade fixed the problem, but I had other issues related to oslo.config, which can be reported in a separate issue. I see errors on nova-api logs:

TRACE nova File "/usr/local/lib/python2.7/dist-packages/keystonemiddleware/openstack/common/memorycache.py", line 21, in <module>
2015-11-04 17:42:20.397 11473 TRACE nova from oslo.config import cfg
2015-11-04 17:42:20.397 11473 TRACE nova ImportError: No module named config
nova ImportError: No module named config

I haven't seen any updates to the README or to the requirements.txt regarding this problem.

**Comment by rafaelfolco** [comment]
For the record(2): fresh deploy with requests==2.7 worked fine. The issue above is probably a side effect of requests issue, fixed downgrading to 2.7 before running ursula allinone.

**Comment by chrisrana** [comment]
I am also getting same probelm.I am using liberty and 
```
glance version is 1.0.0 
python version is 2.7.11

```
glance image-show command  works in root user but fails ubuntu user.
