### ISSUE TITLE
Enable rabbit heart beat and timeout in openstack services

### ISSUE THREAD

**Issue by j2sol** [blueboxgroup/ursula#1343]
With Kilo, oslo.messaging grew the ability to heartbeat to rabbit (enabled by default) and to have a timeout client side to reset connection (not enabled by default). We should enable the timeout to a reasonable time, like say 30 seconds.

This is typically done in a service config file under the header
`[oslo_messaging_rabbit]`

with the setting
```
heartbeat_timeout_threshold = 30
```

however check the config reference in each service to be certain. Setting this should provide a bit more stability in our services around rabbit disconnects or HA failovers.

Would really like to get this in for the 2.0 release.

This also requires kombu>=3.0.7 and amqp>=1.4.0 so be sure those are expressed in the places we install those packages.

**Comment by agireud** [comment]
Looks promising, I can get started taking a look at this.
This should help with migrations.

**Comment by agireud** [comment]
Another one bites the dust!
