### ISSUE TITLE
Do not monitor l3-router placement when external network type is not local

### ISSUE THREAD

**Issue by j2sol** [blueboxgroup/ursula#1435]
When the network type is not local, it doesn't matter where the agents run, they'll work on either controller.

**Comment by j2sol** [comment]
Should be able to check whether the "external" network is of type "local" or not to drive whether this check gets applied.

**Comment by bdrich** [comment]
Can we close this? Looks like it's been fixed already.
https://github.com/blueboxgroup/ursula/commit/f42947bcd1fa9b287872ba6cec1257b8c30f50f3
