### ISSUE TITLE
Swift motd step fails deploying from source

### ISSUE THREAD

**Issue by epwn** [blueboxgroup/ursula#1437]
Because of the changes in PR 1428, swift will fail when appending to the motd file. Workaround is to change destination from /etc/motd.tail to /etc/ursula-release

**Comment by j2sol** [comment]
Good catch. Are you preparing a PR for this?

**Comment by epwn** [comment]
yep, should be up once @CullenTaylor confirms.

**Comment by CullenTaylor** [comment]
@epwn :thumbsup: good to make the PR.

**Comment by j2sol** [comment]
This was fixed.

**Comment by epwn** [comment]
Refer to fix: https://github.com/blueboxgroup/ursula/pull/1440 for future reference
