### ISSUE TITLE
tty is hardcoded in ursula/roles/common/tasks/main.yml 

### ISSUE THREAD

**Issue by openstacks** [blueboxgroup/ursula#1472]
tty is hardcoded in ursula/roles/common/tasks/main.yml 

 Include serial console before kernel-tuning to build serial_console_cmdline
 include: serial-console.yml tty=ttyS0
  tags: ['prereboot']

But X3550 server uses another com ttyS1, So it doesn't work on X3550 server.

**Comment by pwplusnick** [comment]
@openstacks If that PR I made is accepted, then you can set the serial console in all.yml by assigning
```yml
common:
....
  serial_console: ttyS1
```

**Comment by pwplusnick** [comment]
@openstacks The PR I made earlier has been merged. You can now specify the serial console to use like I did in my previous comment.

**Comment by pwplusnick** [comment]
@j2sol This issue is ready to be closed.
