### ISSUE TITLE
Problem downloading packages from hwraid

### ISSUE THREAD

**Issue by jerrygb** [blueboxgroup/ursula#1583]
We receive an md5 hash mismatch downloading packages.

```Downloading https://apt-mirror.openstack.blueboxgrid.com/hwraid/ubuntu/pool-precise/cciss-vol-status_1.10-1hwraid1_amd64.deb...
ERROR: unable to update: download errors:
  https://apt-mirror.openstack.blueboxgrid.com/hwraid/ubuntu/pool-precise/cciss-vol-status_1.10-1hwraid1_amd64.deb: md5 hash mismatch "3374ad58a63a6d00aa82d4283aea8fb0" != "4e3f244a7910f189b325899c8bd0571f"```

**Comment by jerrygb** [comment]
We see some changes in the release file as of yesterday. Maybe the update caused the error?

https://apt-mirror.openstack.blueboxgrid.com/hwraid/ubuntu/dists/precise/Release

Thanks.

**Comment by j2sol** [comment]
I've re-run our mirroring script to try to get updated files. Please retry.

**Comment by jerrygb** [comment]
Hi Jesse,

Thank you for the reply. Now we have a sync error on another package.

```Downloading https://apt-mirror.openstack.blueboxgrid.com/hwraid/ubuntu/pool-precise/3dm2_2.11.00.019+10.2.1+KB16625-1_i386.deb...
ERROR: unable to update: download errors:
  https://apt-mirror.openstack.blueboxgrid.com/hwraid/ubuntu/pool-precise/cciss-vol-status_1.10-1hwraid1_amd64.deb: md5 hash mismatch "3374ad58a63a6d00aa82d4283aea8fb0" != "4e3f244a7910f189b325899c8bd0571f"```

Thanks,
Jerry

**Comment by jerrygb** [comment]
Hi Jesse,

So, if we take a look at https://apt-mirror.openstack.blueboxgrid.com/hwraid/ubuntu/dists/precise/main/binary-amd64/Packages

Notice that md5sum for this package is 4e3f244a7910f189b325899c8bd0571f.

But when we download it and check the sum, its 3374ad58a63a6d00aa82d4283aea8fb0

root@9d24cee1d4f9:/# wget https://apt-mirror.openstack.blueboxgrid.com/hwraid/ubuntu/pool-precise/cciss-vol-status_1.10-1hwraid1_amd64.deb
--2016-02-17 16:19:51--  https://apt-mirror.openstack.blueboxgrid.com/hwraid/ubuntu/pool-precise/cciss-vol-status_1.10-1hwraid1_amd64.deb
Resolving apt-mirror.openstack.blueboxgrid.com (apt-mirror.openstack.blueboxgrid.com)... 173.247.98.12
Connecting to apt-mirror.openstack.blueboxgrid.com (apt-mirror.openstack.blueboxgrid.com)|173.247.98.12|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31294 (31K) [application/x-debian-package]
Saving to: 'cciss-vol-status_1.10-1hwraid1_amd64.deb'

100%[======================================================================================================================================>] 31,294      --.-K/s   in 0.02s   

2016-02-17 16:19:51 (1.86 MB/s) - 'cciss-vol-status_1.10-1hwraid1_amd64.deb' saved [31294/31294]

root@9d24cee1d4f9:/# md5
bash: md5: command not found
root@9d24cee1d4f9:/# md5sum cciss-vol-status_1.10-1hwraid1_amd64.deb
3374ad58a63a6d00aa82d4283aea8fb0  cciss-vol-status_1.10-1hwraid1_amd64.deb

Thanks,
Jerry

**Comment by j2sol** [comment]
This should be fixed as of this morning.

**Comment by jerrygb** [comment]
Thank you @j2sol for the update.
