### ISSUE TITLE
Problem bringing up Percona cluster

### ISSUE THREAD

**Issue by jzer7** [blueboxgroup/ursula#1616]
I apologize, I can read ansible, but not write a fix.

**Problem**: Similar to `envs/example/standard/hosts`, I configured 2 nodes to run the `db` role.  Using Ubuntu 14.04.4, the firewall set up by Ursula prevents communication between nodes in the Percona cluster.  The first node is set in bootstrap mode, which succeeds, but the second node fails the play "bootstrap any secondary nodes".

**Fix**: open up these ports (3306, 4444, 4567 and 4568)  as required by documentation (https://www.percona.com/doc/percona-xtradb-cluster/5.6/howtos/ubuntu_howto.html).

    for port in 3306 4444 4567 4568; do
        sudo iptables -A ufw-user-input -p tcp --dport $port -j ACCEPT
    done

**Comment by j2sol** [comment]
There is a variable, `undercloud_cidr`, that defines the IP space that all of the physical nodes exist on. There is a task in `roles/common/tasks/ufw.yml` that opens up the firewall on every device to accept incoming connections from any other device on that network space. This is how we get percona to talk to each other without restriction.  In your environment, be sure to define `undercloud_cidr` correctly and things will work for you.
