### ISSUE TITLE
Juno release branch

### ISSUE THREAD

**Issue by jerrygb** [blueboxgroup/ursula#1871]
Hi,

May I know if you have Juno release branch available? I suspect we could use the giftwrap and ursula/master, but there would still be a lot of changes in terms of configuration files and such.

We happen to have older stack running on Juno that uses chef. We would love to start converging to the ursula automation (quite possibly to master branch in the future). But before we do that, we need to maintain the existing infrastructure for a little while.  

Thank you.

**Comment by j2sol** [comment]
https://github.com/blueboxgroup/ursula/tree/RELEASE-1.3.x  this branch was the latest work we did for Juno. It never coalesced into a release, the RELEASE-1.2.x was the last one that did, but 1.3 is some bug fixes on top of 1.2.x. Still all Juno.

**Comment by jerrygb** [comment]
Thank you 👍
