### ISSUE TITLE
The number of processes is not correct found by /etc/sensu/plugins/check-procs.rb script

### ISSUE THREAD

**Issue by openstacks** [blueboxgroup/ursula#2200]
### Defect: 
The number of processes is not correct found by /etc/sensu/plugins/check-procs.rb script.

When we use this scripts to monitor RabbitMq service, Both rabbitmq and sensu check process are counted which make sensu client report ""unexpected number of rabbitmq processes",

It should only counted RabbitMq process. 

### How to fix it?
we should add a parameter -u rabbitmq:
/etc/sensu/plugins/check-procs.rb -p rabbitmq -w 15 -c 30 -W 1 -C 1 -u rabbitmq

https://github.com/blueboxgroup/ursula/blob/master/roles/rabbitmq/tasks/monitoring.yml

```
- name: rabbit process check
  sensu_process_check: service=rabbitmq
  args="-p 'rabbitmq' -w 15 -c 30 -W 1 -C 1 -u rabbitmq"
  notify: restart sensu-client
```

### Here are test log:

blueboxadmin@ds0084:/etc/sensu/conf.d/checks$ ps axwwo user,pid,vsz,rss,pcpu,state,command|grep rabbitmq && /etc/sensu/plugins/check-procs.rb -p rabbitmq -w 15 -c 30 -W 1 -C 1
rabbitmq  5102   9544  2628  0.0 S /usr/lib/erlang/erts-7.3/bin/epmd -daemon
rabbitmq  5217   4440   708  0.0 S /bin/sh -e /usr/lib/rabbitmq/bin/rabbitmq-server
rabbitmq  5559 5692376 229420 3.1 S /usr/lib/erlang/erts-7.3/bin/beam.smp -W w -A 64 -P 1048576 -K true -B i -- -root /usr/lib/erlang -progname erl -- -home /var/lib/rabbitmq -- -pa /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.1/ebin -noshell -noinput -s rabbit boot -sname rabbit@ds0084 -boot start_sasl -kernel inet_default_connect_options [{nodelay,true}] -rabbit tcp_listeners [{"0.0.0.0",5672}] -sasl errlog_type error -sasl sasl_error_logger false -rabbit error_logger {file,"/var/log/rabbitmq/rabbit@ds0084.log"} -rabbit sasl_error_logger {file,"/var/log/rabbitmq/rabbit@ds0084-sasl.log"} -rabbit enabled_plugins_file "/etc/rabbitmq/enabled_plugins" -rabbit plugins_dir "/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.1/plugins" -rabbit plugins_expand_dir "/var/lib/rabbitmq/mnesia/rabbit@ds0084-plugins-expand" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false -mnesia dir "/var/lib/rabbitmq/mnesia/rabbit@ds0084" -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672
rabbitmq  6051   7456   428  0.0 S inet_gethost 4
rabbitmq  6052  13776   824  0.0 S inet_gethost 4

_**sensu     9659   4440   648  0.0 S sh -c sudo /etc/sensu/plugins/check-rabbitmq-queues.rb --timeout 2
root      9660  66284  2064  0.0 S sudo /etc/sensu/plugins/check-rabbitmq-queues.rb --timeout 2
root      9669  32096  9012  0.0 S /opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-rabbitmq-queues.rb --timeout 2

root      9691   8616   664  0.0 S /usr/bin/timeout -s 9 2s /usr/sbin/rabbitmqctl list_queues -p /
root      9698   4440   676  0.0 S /bin/sh /usr/sbin/rabbitmqctl list_queues -p /**_

_**sensu     9728   4440   648  0.0 S sh -c sudo /etc/sensu/plugins/check-rabbitmq-queues.rb -t number -w 1860 -c 3720 --timeout 2
root      9730  66284  2060  0.0 S sudo /etc/sensu/plugins/check-rabbitmq-queues.rb -t number -w 1860 -c 3720 --timeout 2
root      9734  32040  9008  0.0 S /opt/sensu/embedded/bin/ruby /etc/sensu/plugins/check-rabbitmq-queues.rb -t number -w 1860 -c 3720 --timeout 2**_

root      9735  65864  1732  0.0 S su rabbitmq -s /bin/sh -c /usr/lib/rabbitmq/bin/rabbitmqctl  'list_queues' '-p' '/'
rabbitmq  9739   4440   648  0.0 S sh -c /usr/lib/rabbitmq/bin/rabbitmqctl  'list_queues' '-p' '/'
rabbitmq  9741 1447844 34496 0.0 S /usr/lib/erlang/erts-7.3/bin/beam.smp -- -root /usr/lib/erlang -progname erl -- -home /var/lib/rabbitmq -- -pa /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.1/ebin -noshell -noinput -hidden -boot start_clean -sasl errlog_type error -mnesia dir "/var/lib/rabbitmq/mnesia/rabbit@ds0084" -s rabbit_control_main -nodename rabbit@ds0084 -extra list_queues -p /

_**root      9875   8616   668  0.0 S /usr/bin/timeout -s 9 2s /usr/sbin/rabbitmqctl list_queues -p /
root      9876   4440   676  0.0 S /bin/sh /usr/sbin/rabbitmqctl list_queues -p /
root      9900  65864  1736  0.0 S su rabbitmq -s /bin/sh -c /usr/lib/rabbitmq/bin/rabbitmqctl  'list_queues' '-p' '/'**_

rabbitmq  9909   4440   648  0.0 S sh -c /usr/lib/rabbitmq/bin/rabbitmqctl  'list_queues' '-p' '/'
rabbitmq  9910 103960  9904  0.0 R /usr/lib/erlang/erts-7.3/bin/beam.smp -- -root /usr/lib/erlang -progname erl -- -home /var/lib/rabbitmq -- -pa /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.1/ebin -noshell -noinput -hidden -boot start_clean -sasl errlog_type error -mnesia dir "/var/lib/rabbitmq/mnesia/rabbit@ds0084" -s rabbit_control_main -nodename rabbit@ds0084 -extra list_queues -p /
bluebox+ 10010  11984   940  0.0 S grep --color=auto rabbitmq

**CheckProcs WARNING: Found 18 matching processes; cmd /rabbitmq/**

**Comment by j2sol** [comment]
Good catch, but slightly wrong fix. The problem is that we're searching for `rabbitmq` instead of `rabbitmq-server`. So we're finding any process with the name `rabbitmq` somewhere in it (except for the one that belongs to the check itself). Simply changing the name narrows down the count to just the rabbitmq-server process.
