### ISSUE TITLE
magic proxy box ?

### ISSUE THREAD

**Issue by paulczar** [blueboxgroup/ursula#642]
after the rubygems issues with the dnssimple ddos yesterday I've been thinking about ways to reduce our reliance on the outside world.   One quick and easy way is to implement a squid proxy that is preseeded with data.

Here is what I've tested, first we set up a squid docker container: 

```
$ docker run --rm  -it -p 0.0.0.0:3128:3128 --name squid --privileged jpetazzo/squid-in-a-can
```

Then we just need to set the `http_proxy` variable to point to squid on that host e.g. `export http_proxy=http://localhost:3128`

Here's are some examples using docker containers as clients:

you can see a 30 second saving on installing a few basic packages:
```
$ time docker run --rm -e http_proxy=http://192.168.50.101:3128 ubuntu apt-get install -yqq curl vim
0.01s user 0.01s system 0% cpu 1:38.42 total
$ time docker run --rm -e http_proxy=http://192.168.50.101:3128 ubuntu apt-get install -yqq curl vim
 0.02s user 0.01s system 0% cpu 1:11.16 total
```

doing something like this as part of an ansible run should speed things up significantly:

```
echo "http_proxy=http://myproxy.domain.com:8080; export http_proxy" >> /etc/bashrc
```

Oh also ...  you can run something like this to save the state of the proxy and push it back up to the docker registry.

```
docker commit squid bluebox/ursula-proxy:0.10
docker push bluebox/ursula-proxy:0.10
```

**Comment by j2sol** [comment]
We now have a magic proxy box.
