### ISSUE TITLE
break out sensu modules into own repo

### ISSUE THREAD

**Issue by paulczar** [blueboxgroup/ursula#766]
rather than looping through the files with a File.glob thingy I think it might be useful to put the sensu modules into their own git repo and then use the git module in ansible to clone it during the run.

**Comment by masteinhauser** [comment]
:+1: We have the same thing for the old Nagios alerts. BPW can help take over and do this process as we'll be ~~stealing~~ using many of the alerts too.

**Comment by sbalukoff** [comment]
+1 Let's please break out the sense modules!

**Comment by j2sol** [comment]
This was done.
